encoder: bert
bert: roberta-large
upsampling: 4
beam_size: 12
dropout: .1
token_dropout: .1
n_decoder_layers: 2
find_unused_parameters: 0
topk: 1
label_smoothing: 0
lr: 5e-05
lr_rate: 10
mu: .9
nu: .9
eps: 1e-12
weight_decay: .01
clip: 5.0
min_freq: 2
fix_len: 20
epochs: 64
patience: 10
batch_size: 100000
eval_batch_size: 10000
warmup_steps: 1000
update_steps: 25
max_len: 64
